/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.petservicesapplication;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zahja
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public SignUp() {
        initComponents();
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                
                new Welcome().setVisible(true);
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petTypeGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JTextField();
        signUpBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dogRadio = new javax.swing.JRadioButton();
        catRadio = new javax.swing.JRadioButton();
        petNameLbl = new javax.swing.JLabel();
        petAgeLbl = new javax.swing.JLabel();
        petNameTxt = new javax.swing.JTextField();
        petAgeTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(242, 178, 73));
        jPanel1.setPreferredSize(new java.awt.Dimension(233, 301));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 98, 77));
        jLabel2.setText("PAWFECT PETS");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 233, 503);

        jPanel2.setBackground(new java.awt.Color(132, 194, 217));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Phone number");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        signUpBtn.setBackground(new java.awt.Color(0, 153, 153));
        signUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Pet type");

        petTypeGrp.add(dogRadio);
        dogRadio.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        dogRadio.setText("Dog");
        dogRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dogRadioStateChanged(evt);
            }
        });

        petTypeGrp.add(catRadio);
        catRadio.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        catRadio.setText("Cat");
        catRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catRadioStateChanged(evt);
            }
        });

        petNameLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        petNameLbl.setText("Pet name");
        petNameLbl.setEnabled(false);

        petAgeLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        petAgeLbl.setText("Pet age");
        petAgeLbl.setEnabled(false);

        petNameTxt.setEnabled(false);

        petAgeTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(petAgeLbl)
                    .addComponent(petNameLbl)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dogRadio)
                                .addGap(43, 43, 43)
                                .addComponent(catRadio)))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(petNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(petAgeTxt))
                            .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dogRadio)
                    .addComponent(catRadio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petNameLbl)
                    .addComponent(petNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petAgeLbl)
                    .addComponent(petAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signUpBtn)
                .addGap(61, 61, 61))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(227, 0, 420, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String idUser, password, name, phone, petType, petName, petAge;

    public void signUp() {
        Customer cust = new Customer(name, phone, 0, "", password, "Customer", idUser);
        int age = Integer.parseInt(petAge);
        Pet pet = new Pet(petType, petName, age);
        int customerID = 0;
        String queryCheckEmail = "Select * from USERS where idUser=?";
        String queryInsertUser = "INSERT INTO USERS (idUser, Password, UName) VALUES (?, ?, ?)";
        String queryInsertCustomer = "INSERT INTO CUSTOMERS (Phone, RewardPoints, User_idUser) VALUES (?, ?, ?)";
        String queryInsertPet = "INSERT INTO PETS (Name, Age, PetType, Customer_idCustomer) VALUES (?,?,?,?)";
        try {
            PreparedStatement checkMailPS, insertUserPS, insertCustomerPS, inesrtPetPS;
            ResultSet checkMailRS, customerIdRS;
            Connection con = MyConnection.connectdb();
            checkMailPS = con.prepareStatement(queryCheckEmail);
            checkMailPS.setString(1, cust.getUserEmail());
            checkMailRS = checkMailPS.executeQuery();
            if (!checkMailRS.next()) {
                insertUserPS = con.prepareStatement(queryInsertUser);
                insertUserPS.setString(1, cust.getUserEmail());
                insertUserPS.setString(2, cust.getPassword());
                insertUserPS.setString(3, cust.getName());
                insertUserPS.executeUpdate();

                insertCustomerPS = con.prepareStatement(queryInsertCustomer, Statement.RETURN_GENERATED_KEYS);
                insertCustomerPS.setString(1, cust.getPhone());
                insertCustomerPS.setInt(2, cust.getReward_points());
                insertCustomerPS.setString(3, cust.getUserEmail());
                insertCustomerPS.executeUpdate();
                customerIdRS = insertCustomerPS.getGeneratedKeys();
                if (customerIdRS.next()) {
                    customerID = customerIdRS.getInt(1);
                }

                inesrtPetPS = con.prepareStatement(queryInsertPet);
                inesrtPetPS.setString(1, pet.getPetName());
                inesrtPetPS.setInt(2, pet.getAge());
                inesrtPetPS.setString(3, pet.getPetType());
                inesrtPetPS.setInt(4, customerID);
                inesrtPetPS.executeUpdate();

                cust.setUserID(customerID + "");
                this.setVisible(false);
                new CustomerMenu(cust).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Email Already Registerd.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        idUser = emailTxt.getText();
        password = passTxt.getText();
        name = nameTxt.getText();
        phone = phoneTxt.getText();
        petType = "";
        if (dogRadio.isSelected()) {
            petType = "Dog";
        }
        if (catRadio.isSelected()) {
            petType = "Cat";
        }
        petName = petNameTxt.getText();
        petAge = petAgeTxt.getText();
        boolean filled = false;

        if (!idUser.equals("") && !password.equals("") && !name.equals("")) {
            if (!petType.equals("") && !petName.equals("") && !petAge.equals("")) {
                filled = true;
                try {
                    int phoneNum = Integer.parseInt(phone);
                    int age = Integer.parseInt(petAge);
                    signUp();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Phone and Pet Age can be only whole numbers ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        if (!filled) {
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields ", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_signUpBtnActionPerformed

    private void dogRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dogRadioStateChanged
        if (dogRadio.isSelected()) {
            petNameTxt.setEnabled(true);
            petAgeTxt.setEnabled(true);
            petNameLbl.setEnabled(true);
            petAgeLbl.setEnabled(true);
        }
    }//GEN-LAST:event_dogRadioStateChanged

    private void catRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catRadioStateChanged
        if (catRadio.isSelected()) {
            petNameTxt.setEnabled(true);
            petAgeTxt.setEnabled(true);
            petNameLbl.setEnabled(true);
            petAgeLbl.setEnabled(true);
        }
    }//GEN-LAST:event_catRadioStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton catRadio;
    private javax.swing.JRadioButton dogRadio;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passTxt;
    private javax.swing.JLabel petAgeLbl;
    private javax.swing.JTextField petAgeTxt;
    private javax.swing.JLabel petNameLbl;
    private javax.swing.JTextField petNameTxt;
    private javax.swing.ButtonGroup petTypeGrp;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton signUpBtn;
    // End of variables declaration//GEN-END:variables
}
